name: Test Orange Building recovery

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
       
         
steps:
- name: Checkout
  uses: actions/checkout@master
- name: Start syncing && Compiling
  image: brock5555/recovery
  commands:
  - bash build.sh
