name: Test Orange Building recovery

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
       
         
steps:

- name: Start syncing && Compiling
  uses: actions/checkout@master
  image: brock5555/recovery
  commands:
  - bash build.sh
